### ISSUE TITLE
Missing file on load

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/mobdb#1]
Seem to be missing a file?

![Igotudis_2022 11 28_101121](https://user-images.githubusercontent.com/66495755/204313218-cada860a-ab8f-4d76-ab37-e9dac61d72b8.png)

**Comment by GetAwayCoxn** [comment]
Perhaps im just misunderstanding the addons message, is this just because no file exists for the zone I was in?

**Comment by ThornyFFXI** [comment]
That is correct, the message is hidden in a later commit but not doing another release until a bit more is added.
