### ISSUE TITLE
Stack traceback when importing AirSkyBoat sql DBs

### ISSUE THREAD

**Issue by plexecutor** [ThornyFFXI/mobdb#11]
Trying to get a more accurate MobDB for the HorizonXI private server. When I acquire the necessary files from ASB and place them in the import folder, I receive a stack traceback when running the import command.

```
Addon 'mobdb' encountered an error during an event callback 'command'. Error: addons/mobdb/import_lsb:342: attempt to index local 'raw' (a nil value)
stack traceback:
addons/mobdb/import_lsb.lua: in function 'BuildDropTable'
addons/mobdb/import_lsb.lua:594: in function 'BuildTables'
\addons\mobdb\\mobdb.lua:91: in function <\addons\mobdb.lua:23>
```

I have confirmed the FFXIPATH variable in import_lsb.lua is set correctly to my game installation path.

**Comment by ThornyFFXI** [comment]
There is no import folder, the folder it loads from is `ashita/config/addons/mobdb/input/*.sql`.  Given the error is also indicating the file wasn't loaded, I would assume you placed the files in the wrong location.

**Comment by ThornyFFXI** [comment]
That said, mobdb's included data files are already generated from a relatively recent ASB branch.  I don't expect you'll gain much(anything?) from making them again, unless Horizon has started committing their custom changes somewhere or made them available.

**Comment by plexecutor** [comment]
Thanks Thorny, didn't realize the data was already included. Regarding the path, I mispoke--I have my sql files placed in .\config\addons\mobdb\input. Mixed up the term input and import in my report.

**Comment by ThornyFFXI** [comment]
To be clear, that specific error is happening here:
```
    local raw = io.open(string.format('%sconfig/addons/mobdb/input/mob_droplist.sql', AshitaCore:GetInstallPath()));
    local lines = raw:lines();```
    
So, I do not believe it to be an actual error in mobdb.  It seems more likely that you have placed the files in the wrong location, or missed the mob_droplist.sql file, or have a permissions issue on your machine.

**Comment by ThornyFFXI** [comment]
Closing this as there was no further comment and the error itself indicates a failure to access input files, not a flaw in the code.
