### ISSUE TITLE
Scaling config window with default Ashita 4.2.0.1+ font settings

### ISSUE THREAD

**Issue by clanofartisans** [ThornyFFXI/mobdb#14]
While the font settings are easy enough to change, if using Ashita's default font settings, the sliders stretch off the right side of the window. Pretty much just a cosmetic issue but figured I'd mention it.

![image](https://github.com/ThornyFFXI/mobdb/assets/12788345/4cd6907c-2bdb-470f-aad5-0b06d1428c5b)

**Comment by ThornyFFXI** [comment]
should be better in 1.17, ty
