### ISSUE TITLE
Truesound icon

### ISSUE THREAD

**Issue by ryzouken** [ThornyFFXI/mobdb#16]
A quick perusal in the files for the mod indicated a lack of a true sound icon for mob aggro.  Is there a method by which this is currently indicated or was it omitted?  Regardless, an icon for truesound would be well received.

**Comment by ThornyFFXI** [comment]
True sound as handled on private servers is not set up as a seperate flag.  True sight effects both sight and sound, whatever the mob detects by.  So, a true sight mob will have both the 'detects by sight' and the 'true sight' icon.  A true sound mob will have both the 'detects by sound' and the 'true sight' icon.

The true sight icon is not indicative of detection method, simply that sneak/invisible are ineffective.

**Comment by ryzouken** [comment]
I see!  Thank you for the information!  I'll close this then.
